window.CHANGELOG_SOURCES = [
	{ slug: "c-to-gun",                         id: "coals-to-gunpowder",               badge: "Coals to Gunpowder" },
	{ slug: "recyclings",                       id: "recycling",                        badge: "Recycling" },
	{ slug: "villager-heal-golem",              id: "villager-heal-golem",              badge: "Villager Heal Golem" },
	{ slug: "villager-heal-villager",           id: "villager-heal-villager",           badge: "Villager Heal Villager" },
	{ slug: "cleric-heal-villager",             id: "cleric-heal-villager",             badge: "Cleric Heal Villager" },
	{ slug: "better-crafts",                    id: "better-crafts",                    badge: "Better Crafts" },
	{ slug: "speed-paths",                      id: "speed-paths",                      badge: "Speed Paths" },
	{ slug: "armorer-heal-golem",               id: "armorer-heal-golem",               badge: "Armorer Heal Golem" },
	{ slug: "lava-source",                      id: "lava-source",                      badge: "Lava Source" },
	{ slug: "better_furnaces",                  id: "better-furnaces",                  badge: "Better Furnaces" },
	{ slug: "cookies-clicker",                  id: "cookie-clicker",                   badge: "Cookie Clicker" },
	{ slug: "villagers-tasks",                  id: "villagers-tasks",                  badge: "Villagers Tasks" },
	{ slug: "better-brewings",                  id: "better-brewings",                  badge: "Better Brewings" },
	{ slug: "better-crafts-old-versions",       id: "better-crafts-old-versions",       badge: "Better Crafts - old versions" },
	{ slug: "better-furnaces-old-versions",     id: "better-furnaces-old-versions",     badge: "Better Furnaces - old versions" },
];
